name: Automatic Stacked PR Annotation
on:
  issue_comment:
    types: [created]
jobs:
  annotate:
    name: Annotate
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/annotate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Automatic Stacked PR Annotation
        uses: luqven/annotate@0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
